# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

title: "Quick start to move logs from Oracle Streaming service to OCI Logging / DataDog / New Relic / Dyna Trace / ElasticSearch"
stackDescription: "This Quick start will setup a fluentD instance in a public subnet of a VCN, install required plugins and create necessary configuration files to connect and move logs grom stream to the target."
schemaVersion: 1.1.0
version: "20200301"
locale: "en"

variableGroups:
- title: ${Messages.solutionsHub.generalConfig()}
  visible: false
  variables:
  - tenancy_ocid
  - current_user_ocid
  - fingerprint
  - private_key_path
  - VCN-CIDR
  - instance_os
  - linux_os_version
  - instance_flex_shape_ocpus
  - instance_flex_shape_memory
  - instance_shape
  - generate_public_ssh_key
  - ssh_public_key
  - public_ssh_key
  - private_ssh_key_path

- title: ${Messages.solutionsHub.requiredConfig()}
  visible: true  
  variables:
  - compartment_ocid
  - region
  - stream_pool_name
  - stream_name
  - stream_partitions
  - fluentD_output_plugin

- title: OCI Logging config
  visible:
    and:
      - or:
        - eq:
          - fluentD_output_plugin
          - "OCI_LOGGING"
  variables:
  - log_group_display_name
  - log_display_name

- title: Data Dog config
  visible:
    and:
      - or:
        - eq:
          - fluentD_output_plugin
          - "DATA_DOG"
  variables:
  - data_dog_api_key

- title: New Relic config
  visible:
    and:
      - or:
        - eq:
          - fluentD_output_plugin
          - "NEW_RELIC"
  variables:
  - new_relic_api_key

- title: Elastic Search config
  visible:
    and:
      - or:
        - eq:
          - fluentD_output_plugin
          - "ELASTIC_SEARCH"
  variables:
  - es_host
  - es_port
  - es_username
  - es_pass

- title: Dyna Trace config
  visible:
    and:
      - or:
        - eq:
          - fluentD_output_plugin
          - "DYNA_TRACE"
  variables:
  - dyna_trace_host_name
  - dyna_trace_api_key

variables:

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: ${Messages.solutionsHub.genericVariables.compartment.title()}
    description: ${Messages.solutionsHub.genericVariables.compartment.description()}

  region:
    type: oci:identity:region:name
    required: true
    title: "Region"
    description: "Region where the stack will be deployed."

  stream_pool_name:
    type: string
    required: false
    title: "Stream pool name"

  stream_name:
    type: string
    required: true
    title: "Stream name"

  stream_partitions:
    type: number
    description: "No of partitions in the stream"
    title: "Stream Partitions"
    required: true

  fluentD_output_plugin:
    type: enum
    title: "Log destination"
    required: true
    default: "OCI_LOGGING"
    enum:
      - OCI_LOGGING
      - DATA_DOG
      - NEW_RELIC
      - DYNA_TRACE
      - ELASTIC_SEARCH

  log_group_display_name:
    type: string
    required: true
    title: "Log Group name"

  log_display_name:
    type: string
    required: true
    title: "Custom Log name"

  data_dog_api_key:
    type: string
    description: "Data Dog API key for authentication"
    title: "Data Dog API Key"
    required: true

  new_relic_api_key:
    type: string
    description: "New Relic API key for authentication"
    title: "New Relic API Key"
    required: true

  es_host:
    type: string
    required: true
    title: "Elastic Search host"
    
  es_port:
    type: string
    required: true
    title: "Elastic Search port"

  es_username:
    type: string
    required: true
    title: "Elastic Search username"

  es_pass:
    type: string
    required: true
    title: "Elastic Search password"
    
  dyna_trace_host_name:
    type: string
    required: true
    title: "DynaTrace host name"

  dyna_trace_api_key:
    type: string
    required: true
    title: "DynaTrace API Key"

